### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by Kit0077** [Laysinity/BLUM-Drop-game-farming-bot#2]
Привет, Бро! Спасибо тебе за твои старания, но не мог бы ты помочь запустить бота? Постоянно получаю одни и те же ошибки, перепробовал все.
![image](https://github.com/Laysinity/BLUM-Drop-game-farming-bot/assets/57114371/1f4a0395-822f-4dcc-b72f-82e6447bd2a2)

**Comment by DanWES567** [comment]
session path должен быть в кавычках и еще справа надо дописать r
![image](https://github.com/Laysinity/BLUM-Drop-game-farming-bot/assets/88350148/9a8b77d8-532b-4d0f-88bb-9a429a53fa23)
