### ISSUE TITLE
проблемы с запуском

### ISSUE THREAD

**Issue by bratosd** [Laysinity/BLUM-Drop-game-farming-bot#4]
при вводе команды python3 main.py пишет:
C:\Users\New\Desktop\BLUM-Drop-game-farming-bot-main>python main.py
Traceback (most recent call last):
  File "C:\Users\New\Desktop\BLUM-Drop-game-farming-bot-main\main.py", line 1, in <module>
    from utils.core import create_sessions
  File "C:\Users\New\Desktop\BLUM-Drop-game-farming-bot-main\utils\__init__.py", line 1, in <module>
    from .blum import Blum
  File "C:\Users\New\Desktop\BLUM-Drop-game-farming-bot-main\utils\blum.py", line 3, in <module>
    from utils.core import logger
  File "C:\Users\New\Desktop\BLUM-Drop-game-farming-bot-main\utils\core\__init__.py", line 2, in <module>
    from .register import create_sessions
  File "C:\Users\New\Desktop\BLUM-Drop-game-farming-bot-main\utils\core\register.py", line 2, in <module>
    from data import config
  File "C:\Users\New\Desktop\BLUM-Drop-game-farming-bot-main\data\config.py", line 15
    SESSIONS_PATH = "C:\Users\New\Desktop\BLUM-Drop-game-farming-bot-main\sessions"
                                                                                   ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

**Comment by Kit0077** [comment]
> при вводе команды python3 main.py пишет: C:\Users\New\Desktop\BLUM-Drop-game-farming-bot-main>python main.py Traceback (most recent call last): File "C:\Users\New\Desktop\BLUM-Drop-game-farming-bot-main\main.py", line 1, in from utils.core import create_sessions File "C:\Users\New\Desktop\BLUM-Drop-game-farming-bot-main\utils__init__.py", line 1, in from .blum import Blum File "C:\Users\New\Desktop\BLUM-Drop-game-farming-bot-main\utils\blum.py", line 3, in from utils.core import logger File "C:\Users\New\Desktop\BLUM-Drop-game-farming-bot-main\utils\core__init__.py", line 2, in from .register import create_sessions File "C:\Users\New\Desktop\BLUM-Drop-game-farming-bot-main\utils\core\register.py", line 2, in from data import config File "C:\Users\New\Desktop\BLUM-Drop-game-farming-bot-main\data\config.py", line 15 SESSIONS_PATH = "C:\Users\New\Desktop\BLUM-Drop-game-farming-bot-main\sessions" ^ SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

Посмотри ответ на мой вопрос, там парень обьяснил

**Comment by Laysinity** [comment]
Замени "\" в пути на "/"
